/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fltr.h"

bool_t
xdr_t_file_cont (XDR *xdrs, t_file_cont *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->t_file_cont_val, (u_int *) &objp->t_file_cont_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_t_file_cont (xdrs, &objp->content))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_errmsg (XDR *xdrs, errmsg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}
