/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fltr.h"

bool_t
xdr_t_flname (XDR *xdrs, t_flname *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, LEN_PATH_MAX))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_flcont (XDR *xdrs, t_flcont *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->t_flcont_val, (u_int *) &objp->t_flcont_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filetype (XDR *xdrs, filetype *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_inf (XDR *xdrs, file_inf *objp)
{
	register int32_t *buf;

	 if (!xdr_t_flname (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_filetype (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_t_flcont (xdrs, &objp->cont))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_err_inf (XDR *xdrs, err_inf *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	switch (objp->num) {
	case 0:
		break;
	default:
		 if (!xdr_string (xdrs, &objp->err_inf_u.msg, LEN_ERRMSG_MAX))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_file_err (XDR *xdrs, file_err *objp)
{
	register int32_t *buf;

	 if (!xdr_file_inf (xdrs, &objp->file))
		 return FALSE;
	 if (!xdr_err_inf (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}
